<?php
//Starts session
session_start();
?>

<html>
<head>
	<title> Weight Brackets </title>

	<style>
	body
		{
		background: rgba(125, 173, 250, 1.0);
		}

	button.backToMenu
		{
		font-size: 1.2vw;	
		text-align: center;
		background: rgba(188, 221, 255, 1.0);
		padding: 1px 10px;
		box-sizing: border-box;
		width: 10vw;
		margin-left: 0.3vw;
		vertical-align: middle;
		}
	
	p.instructions
		{
		font-size: 1.7vw;
		font-family: sans-serif;
		text-align: center;
		margin: auto;
		margin-top: 3%;
		margin-bottom: 4%;
		}	

	table, th, td
		{
		font-family: sans-serif;
		text-align: center;
		margin: auto;
		margin-top: 2%;
		border: 7px solid rgba(216, 235, 255, 1.0);
		border-collapse: collapse;		
		}

	tr.headers
		{
		background: rgba(141, 217, 255, 1.0);
		font-size: 1.6vw;
		}
	
	input.costInput
		{
		font-size: 1.4vw;
		box-sizing: border-box;
		background: rgba(188, 221, 255, 1.0);
		width: 13vw;
		text-align: center;
		-webkit-appearance: none;
		-moz-appearance: textfield;
		vertical-align: middle;	
		}
		
	input.weightInput
		{
		font-size: 1.4vw;
		box-sizing: border-box;
		background: rgba(188, 221, 255, 1.0);
		width: 13vw;
		text-align: center;
		-webkit-appearance: none;
		-moz-appearance: textfield;
		vertical-align: middle;	
		}
	
	button.submitBracket
		{
		font-size: 1.4vw;	
		text-align: center;
		background: rgba(188, 221, 255, 1.0);
		padding: 1px 10px;
		box-sizing: border-box;
		width: 18vw;
		vertical-align: middle;
		}
	

	</style>

	<script type="text/javascript">
		window.addEventListener('keydown',function(e){if(e.keyIdentifier=='U+000A'||e.keyIdentifier=='Enter'||e.keyCode==13){if(e.target.nodeName=='INPUT'&&e.target.type=='number'){e.preventDefault();return false;}}},true);
	</script>

</head>

<body>
<?php
	//Sets database variables for weight bracket db
	$usernameC = "z1838064";
	$passwordC = "1999Dec01";
	$hostnameC = "courses";
	$databaseC = "z1838064";
	$dbWeights = "Weights";
	
	$dbCost = "Cost";
	$dbMinW = "MinW";
	$dbMaxW = "MaxW";
	$dbBracketID = "BracketID";
	$numBrackets = "5";
	
	//Post and Session variable setting
	if(!isset($_POST['changed']))
		$_POST['changed'] = 'false';

	//Return to menu button
	echo "
	<form method='GET' action='./adminInterfaceMenu.php'>
		<button class='backToMenu' type='submit'>Back to Menu</button>
	</form>";

	//Updates database with changed table data
	if($_POST['changed'] == 'true')
		{
		$pdo = safeConnectC();
		$sql = "UPDATE " . $dbWeights . " SET " . $dbMinW . " = " . $_POST['min'] . ", " . $dbMaxW . " = " . $_POST['max'] . ", " . $dbCost . " = " . $_POST['cost'] . " WHERE " . $dbBracketID . " = " . $_POST['id'] . ";";
		$pdo -> query($sql);
		}

	//Gets 2d array of all weight brackets
	$pdo = safeConnectC();
	$sql = "SELECT * FROM " . $dbWeights . ";";
	$result = $pdo->query($sql);
	$bracketArray = $result->fetchAll();

	//Instructions
	echo "
		<p class='instructions'> Adjust each bracket and submit the changes individually. </p>";
	
	//Shows a table with all weight brackets with changeable fields and a submit button to submit changes
	echo "
	<table>
		<tr class=headers>
			<td> Minimum Weight </td>
			<td> Maximum Weight </td>
			<td> Shipping Cost </td>
			<td> Submit Bracket Changes </td>
		</tr>";
	
	//Shows table
	foreach($bracketArray as $var)
		{
		echo "
		<tr>
			<form method='POST'>
			<input type='hidden' name='changed' value='true'> </input>
			<input type='hidden' name='id' value='" . $var[$dbBracketID] . "'> </input>
			<td> <input class='weightInput' type='number' step='0.01' min='0' name='min' value='" . $var[$dbMinW] . "'> </input> </td>
			<td> <input class='weightInput' type='number' step='0.01' min='0' max='99999.99' name='max' value='" . $var[$dbMaxW] . "'> </input> </td>
			<td> <input class='costInput' type='number' step='0.01' min='0' name='cost' value='" . $var[$dbCost] . "'> </input> </td>
			<td> <button class='submitBracket' type='submit'> Submit Changes </button> </td>		
			</form>
		</tr>";	
		}
	
//==========================================Functions========================================//
	function safeConnectC()
		{
		//Does a fail-conscious connection
		try
			{
			//Creates a connection to the database specified and makes a variable 
			//for the connection object
			$dsn = "mysql:host=" . $GLOBALS['hostnameC'] . ";dbname=" . $GLOBALS['databaseC'];
			$pdo = new PDO($dsn, $GLOBALS['usernameC'], $GLOBALS['passwordC']);
			}
		
		//Catches the exception generated by a failed connection
		catch(PDOexception $e)
			{
			echo "Connection to database failed: " . $e->getMessage();
			}		

		//Returns connection object
		return $pdo;
			
		}	
	
?>

</body>
</html>
