<?php
   	//Sets database variables for Catalog
	$usernameC = "z1838064";
	$passwordC = "1999Dec01";
	$hostnameC = "courses";
	$databaseC = "z1838064";
	$dbCatalog = "Product";
	$dbOrders = "Orders";

	//Sets database variables for Legacy Database
	$usernameL = "student";
	$passwordL = "student";
	$hostnameL = "blitz.cs.niu.edu";
	$databaseL = "csci467";
	$dbParts = "parts"; 
	
	function safeConnectC()
        {
        //Does a fail-conscious connection
        try
            {
            //Creates a connection to the database specified and makes a variable 
            //for the connection object
            $dsn = "mysql:host=" . $GLOBALS['hostnameC'] . ";dbname=" . $GLOBALS['databaseC'];
            $pdo = new PDO($dsn, $GLOBALS['usernameC'], $GLOBALS['passwordC']);
            }

        //Catches the exception generated by a failed connection
        catch(PDOexception $e)
            {
            echo "Connection to database failed: " . $e->getMessage();
            }

        //Returns connection object
        return $pdo;

        }
    
	function safeConnectL()
        {
        //Does a fail-conscious connection
        try
            {
            //Creates a connection to the database specified and makes a variable 
            //for the connection object
            $dsn = "mysql:host=" . $GLOBALS['hostnameL'] . ";dbname=" . $GLOBALS['databaseL'];
            $pdo = new PDO($dsn, $GLOBALS['usernameL'], $GLOBALS['passwordL']);
            }

        //Catches the exception generated by a failed connection
        catch(PDOexception $e)
            {
            echo "Connection to database failed: " . $e->getMessage();
            }

        //Returns connection object
        return $pdo;

        }
?>