<html>
    <head>
        <title>Metalopaclypse</title>
        <link rel='stylesheet' href='selection.css'>
    </head>
    <body background="">

    <div class='topnav'>
        <h1 class='pageTitle'>Catalog</h1>
        <a href="homePage.php">Home</a>
    </div>
    <?php   	
		//Sets database variables for Catalog
    	$usernameC = "z1838064";
    	$passwordC = "1999Dec01";
    	$hostnameC = "courses";
    	$databaseC = "z1838064";
    	$dbCatalog = "Product";
    	$dbOrders = "Orders";
		$dbWeights = "Weights";

    	//Sets database variables for Legacy Database
    	$usernameL = "student";
    	$passwordL = "student";
    	$hostnameL = "blitz.cs.niu.edu";
    	$databaseL = "csci467";
    	$dbParts = "parts";

    	function safeConnectC()
            {
            //Does a fail-conscious connection
            try
                {
                //Creates a connection to the database specified and makes a variable
                //for the connection object
                $dsn = "mysql:host=" . $GLOBALS['hostnameC'] . ";dbname=" . $GLOBALS['databaseC'];
                $pdo = new PDO($dsn, $GLOBALS['usernameC'], $GLOBALS['passwordC']);
                }

            //Catches the exception generated by a failed connection
            catch(PDOexception $e)
                {
                echo "Connection to database failed: " . $e->getMessage();
                }

            //Returns connection object
            return $pdo;

            }

    	function safeConnectL()
            {
            //Does a fail-conscious connection
            try
                {
                //Creates a connection to the database specified and makes a variable
                //for the connection object
                $dsn = "mysql:host=" . $GLOBALS['hostnameL'] . ";dbname=" . $GLOBALS['databaseL'];
                $pdo = new PDO($dsn, $GLOBALS['usernameL'], $GLOBALS['passwordL']);
                }

            //Catches the exception generated by a failed connection
            catch(PDOexception $e)
                {
                echo "Connection to database failed: " . $e->getMessage();
                }

            //Returns connection object
            return $pdo;

            }
?>
<form action='./Checkout.php' method='post'>
  <label> Select Your Products <label>
<?php
//fetch display data from database using PDO

		$pdo = safeConnectL();
        $sql = "SELECT * FROM parts";
        $d = $pdo->query($sql);

?>
<table border="3" cellpadding="5" cellspacing="5" align="center">
<tr>
  <th>Number</th>
  <th>Description</th>
  <th>Price</th>
</tr>

<?php  foreach($d as $data)
{
?>
<tr>
  <td><?php echo $data['number']; ?></td>
  <td><?php echo $data['description']; ?></td>
  <td><?php echo $data['price']; ?></td>
</tr>
<?php
}
?>
</table>

</body>
</html>
//
